name = "namachan10777dev"
main = "./dist/_worker.js"
compatibility_date = "2025-07-12"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
binding = "ASSET"
directory = "./dist"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_id = "c609b018-bc8e-487d-bdcd-e0d31c6bfdd8"
preview_database_id = "94e88de8-fcfa-4cc4-825d-d8c22f3e82e4"
database_name = "db"
remote = true

[[kv_namespaces]]
binding = "KV"
id = "d2c3b9591768403db8b733704da4b3d2"
preview_id = "b986f9deaca54fa2866fa3ffa74a2e4e"
remote = true

[[r2_buckets]]
binding = "R2"
bucket_name = "namachan10777dev"
preview_bucket_name = "namachan10777dev-preview"
remote = true

[images]
binding = "IMAGES"

[vars]
TURNSTILE_SITE_KEY = "1x00000000000000000000AA"
TURNSTILE_SECRET_KEY = "1x0000000000000000000000000000000AA"
